# Generated by Django 2.1.1 on 2018-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
