# Generated by Django 2.1.2 on 2018-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
