# Generated by Django 2.1.2 on 2018-10-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20181012_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='guard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Guardian'),
        ),
    ]
